export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const FETCH_NOTIFICATION = "FETCH_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const DELETE_ALL_NOTIFICATION = "DELETE_ALL_NOTIFICATION";